import { UserProfile } from '@/types/user';
import { Risk, RiskCategory } from '@/types/risk';
import { Control } from '@/types/control';
import { ComplianceItem } from '@/types/compliance';
import { AuditLog } from '@/types/audit';
import { Evidence } from '@/types/evidence';

export const mockUsers: UserProfile[] = [
  {
    id: 'user-1',
    email: 'alice@company.com',
    fullName: 'Alice Johnson',
    role: 'admin',
    department: 'Compliance',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-28',
  },
  {
    id: 'user-2',
    email: 'bob@company.com',
    fullName: 'Bob Smith',
    role: 'analyst',
    department: 'Risk Management',
    createdAt: '2024-01-05',
    updatedAt: '2024-01-28',
  },
  {
    id: 'user-3',
    email: 'carol@company.com',
    fullName: 'Carol Williams',
    role: 'manager',
    department: 'Operations',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-28',
  },
];

export const mockRiskCategories: RiskCategory[] = [
  { id: '1', name: 'Operational', description: 'Day-to-day operational risks', color: '#3b82f6' },
  { id: '2', name: 'Financial', description: 'Financial stability risks', color: '#10b981' },
  { id: '3', name: 'Compliance', description: 'Regulatory compliance risks', color: '#f59e0b' },
  { id: '4', name: 'Strategic', description: 'Long-term strategy risks', color: '#8b5cf6' },
  { id: '5', name: 'Reputational', description: 'Brand and reputation risks', color: '#ef4444' },
  { id: '6', name: 'Technology', description: 'IT and cybersecurity risks', color: '#06b6d4' },
];

export const mockRisks: Risk[] = [
  {
    id: 'risk-1',
    title: 'Data Breach',
    description: 'Unauthorized access to sensitive customer data',
    categoryId: '6',
    category: mockRiskCategories[5],
    likelihood: 3,
    impact: 5,
    riskScore: 15,
    status: 'assessed',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdBy: 'user-2',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-28',
  },
  {
    id: 'risk-2',
    title: 'Regulatory Non-Compliance',
    description: 'Failure to meet GDPR requirements',
    categoryId: '3',
    category: mockRiskCategories[2],
    likelihood: 2,
    impact: 4,
    riskScore: 8,
    status: 'identified',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdBy: 'user-1',
    createdAt: '2024-01-20',
    updatedAt: '2024-01-25',
  },
  {
    id: 'risk-3',
    title: 'System Downtime',
    description: 'Critical infrastructure failure',
    categoryId: '1',
    category: mockRiskCategories[0],
    likelihood: 2,
    impact: 4,
    riskScore: 8,
    status: 'mitigated',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdBy: 'user-2',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-22',
  },
  {
    id: 'risk-4',
    title: 'Budget Overrun',
    description: 'Project expenses exceed allocated budget',
    categoryId: '2',
    category: mockRiskCategories[1],
    likelihood: 3,
    impact: 3,
    riskScore: 9,
    status: 'identified',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdBy: 'user-1',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-26',
  },
  {
    id: 'risk-5',
    title: 'Key Person Dependency',
    description: 'Critical functions dependent on single individual',
    categoryId: '4',
    category: mockRiskCategories[3],
    likelihood: 4,
    impact: 3,
    riskScore: 12,
    status: 'assessed',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdBy: 'user-2',
    createdAt: '2024-01-12',
    updatedAt: '2024-01-27',
  },
];

export const mockControls: Control[] = [
  {
    id: 'control-1',
    title: 'Multi-Factor Authentication',
    description: 'Implement MFA for all system access',
    controlType: 'preventive',
    effectiveness: 'high',
    status: 'implemented',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdBy: 'user-2',
    createdAt: '2024-01-08',
    updatedAt: '2024-01-28',
  },
  {
    id: 'control-2',
    title: 'Security Awareness Training',
    description: 'Quarterly training for all employees',
    controlType: 'preventive',
    effectiveness: 'medium',
    status: 'implemented',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdBy: 'user-1',
    createdAt: '2024-01-05',
    updatedAt: '2024-01-28',
  },
  {
    id: 'control-3',
    title: 'Data Encryption',
    description: 'Encrypt all data at rest and in transit',
    controlType: 'preventive',
    effectiveness: 'high',
    status: 'implemented',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdBy: 'user-2',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-28',
  },
  {
    id: 'control-4',
    title: 'Audit Logging',
    description: 'Comprehensive audit trail for all system actions',
    controlType: 'detective',
    effectiveness: 'high',
    status: 'under_review',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdBy: 'user-2',
    createdAt: '2024-01-12',
    updatedAt: '2024-01-27',
  },
  {
    id: 'control-5',
    title: 'Disaster Recovery Plan',
    description: 'Documented and tested disaster recovery procedures',
    controlType: 'corrective',
    effectiveness: 'medium',
    status: 'planned',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdBy: 'user-1',
    createdAt: '2024-01-20',
    updatedAt: '2024-01-25',
  },
];

export const mockComplianceItems: ComplianceItem[] = [
  {
    id: 'comp-1',
    framework: 'GDPR',
    requirementId: 'GDPR-5.1',
    title: 'Data Protection Officer',
    description: 'Designate and notify DPO to supervisory authority',
    status: 'compliant',
    priority: 'critical',
    dueDate: '2024-02-15',
    ownerId: 'user-1',
    ownerName: 'Alice Johnson',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-28',
    evidenceCount: 3,
  },
  {
    id: 'comp-2',
    framework: 'SOC2',
    requirementId: 'CC6.1',
    title: 'Logical Access Controls',
    description: 'Implement user access control mechanisms',
    status: 'in_progress',
    priority: 'high',
    dueDate: '2024-02-28',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdAt: '2024-01-05',
    updatedAt: '2024-01-28',
    evidenceCount: 2,
  },
  {
    id: 'comp-3',
    framework: 'ISO27001',
    requirementId: 'A.12.4.1',
    title: 'Event Logging',
    description: 'Recording user activities and system events',
    status: 'not_started',
    priority: 'medium',
    dueDate: '2024-03-31',
    ownerId: 'user-2',
    ownerName: 'Bob Smith',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-20',
    evidenceCount: 0,
  },
  {
    id: 'comp-4',
    framework: 'GDPR',
    requirementId: 'GDPR-32',
    title: 'Data Protection Impact Assessment',
    description: 'Conduct DPIA for high-risk processing',
    status: 'compliant',
    priority: 'high',
    dueDate: '2024-02-01',
    ownerId: 'user-1',
    ownerName: 'Alice Johnson',
    createdAt: '2024-01-08',
    updatedAt: '2024-01-28',
    evidenceCount: 4,
  },
];

export const mockEvidence: Evidence[] = [
  {
    id: 'evidence-1',
    title: 'MFA Implementation Report',
    description: 'Verification of MFA rollout completion',
    fileUrl: '/documents/mfa-report.pdf',
    fileName: 'mfa-report.pdf',
    fileType: 'pdf',
    fileSize: 2048000,
    relatedTo: 'control',
    relatedId: 'control-1',
    relatedName: 'Multi-Factor Authentication',
    uploadedBy: 'user-2',
    uploadedByName: 'Bob Smith',
    uploadedAt: '2024-01-28',
    verified: true,
    verifiedBy: 'user-1',
    verifiedByName: 'Alice Johnson',
    verifiedAt: '2024-01-28',
  },
  {
    id: 'evidence-2',
    title: 'GDPR DPO Notification',
    description: 'Official notification to supervisory authority',
    fileUrl: '/documents/dpo-notification.pdf',
    fileName: 'dpo-notification.pdf',
    fileType: 'pdf',
    fileSize: 512000,
    relatedTo: 'compliance_item',
    relatedId: 'comp-1',
    relatedName: 'Data Protection Officer',
    uploadedBy: 'user-1',
    uploadedByName: 'Alice Johnson',
    uploadedAt: '2024-01-25',
    verified: true,
    verifiedBy: 'user-1',
    verifiedByName: 'Alice Johnson',
    verifiedAt: '2024-01-25',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    userId: 'user-2',
    userName: 'Bob Smith',
    action: 'created',
    entityType: 'risk',
    entityId: 'risk-1',
    entityName: 'Data Breach',
    timestamp: '2024-01-28T10:30:00Z',
    description: 'New risk identified',
  },
  {
    id: 'audit-2',
    userId: 'user-1',
    userName: 'Alice Johnson',
    action: 'updated',
    entityType: 'risk',
    entityId: 'risk-1',
    entityName: 'Data Breach',
    oldValues: { status: 'identified', riskScore: 15 },
    newValues: { status: 'assessed', riskScore: 15 },
    timestamp: '2024-01-28T14:15:00Z',
    description: 'Risk status updated to assessed',
  },
  {
    id: 'audit-3',
    userId: 'user-2',
    userName: 'Bob Smith',
    action: 'created',
    entityType: 'evidence',
    entityId: 'evidence-1',
    entityName: 'MFA Implementation Report',
    timestamp: '2024-01-28T09:00:00Z',
    description: 'Evidence uploaded for control',
  },
];
