"""add_evidence_ai_summary

Revision ID: 07390fbae0fd
Revises: 3cac8bba9858
Create Date: 2026-03-16 21:27:52.653138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07390fbae0fd'
down_revision: Union[str, Sequence[str], None] = '3cac8bba9858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'risks', 'risk_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.drop_column('evidence', 'ai_summary')
    # ### end Alembic commands ###
