"""Add framework and control library

Revision ID: 1ea368a796ae
Revises: f1f4459c2ba3
Create Date: 2026-03-13 03:40:00.686435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea368a796ae'
down_revision: Union[str, Sequence[str], None] = 'f1f4459c2ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frameworks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('framework_controls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('control_applicability', sa.Column('framework_control_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'control_applicability', 'framework_controls', ['framework_control_id'], ['id'])
    op.add_column('organizations', sa.Column('framework_id', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column('isms_scope', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'frameworks', ['framework_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'isms_scope')
    op.drop_column('organizations', 'framework_id')
    op.drop_constraint(None, 'control_applicability', type_='foreignkey')
    op.drop_column('control_applicability', 'framework_control_id')
    op.drop_table('framework_controls')
    op.drop_table('frameworks')
    # ### end Alembic commands ###
