"""add_organization_id_to_controls

Revision ID: 36acc6ed0d23
Revises: b6c79cc3e5ac
Create Date: 2026-06-12 08:34:16.074803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add_organization_id_to_controls

Revision ID: 36acc6ed0d23
Revises: b6c79cc3e5ac
Create Date: 2026-06-12 08:34:16.074803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36acc6ed0d23'
down_revision: Union[str, Sequence[str], None] = 'b6c79cc3e5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'controls', 'organizations', ['organization_id'], ['id'])
    
    # Populate existing controls with the real organization ID
    op.execute("UPDATE controls SET organization_id = '24de3639-ee40-4563-a207-dd66436a0da8' WHERE organization_id IS NULL")
    
    op.alter_column('tickets', 'source_audit_log_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'source_audit_log_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('organizations', 'ticket_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('document_analyses', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'controls', type_='foreignkey')
    op.drop_column('controls', 'organization_id')
    # ### end Alembic commands ###
