"""drop_risk_category_fk

Revision ID: 3cac8bba9858
Revises: 9a4338637084
Create Date: 2026-03-15 22:43:15.090569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cac8bba9858'
down_revision: Union[str, Sequence[str], None] = '9a4338637084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('risks_category_id_fkey'), 'risks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('risks_category_id_fkey'), 'risks', 'risk_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
