"""Add asset CIA values and risk assessment fields

Revision ID: 43d8a6d5e7fe
Revises: 1ea368a796ae
Create Date: 2026-03-13 03:56:30.567010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d8a6d5e7fe'
down_revision: Union[str, Sequence[str], None] = '1ea368a796ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('confidentiality', sa.Enum('low', 'medium', 'high', name='ciavalue'), nullable=True))
    op.add_column('assets', sa.Column('integrity', sa.Enum('low', 'medium', 'high', name='ciavalue'), nullable=True))
    op.add_column('assets', sa.Column('availability', sa.Enum('low', 'medium', 'high', name='ciavalue'), nullable=True))
    op.add_column('risk_control_mappings', sa.Column('framework_control_id', sa.UUID(), nullable=True))
    op.alter_column('risk_control_mappings', 'control_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'risk_control_mappings', 'framework_controls', ['framework_control_id'], ['id'])
    op.add_column('risks', sa.Column('asset_id', sa.UUID(), nullable=True))
    op.add_column('risks', sa.Column('threat', sa.Text(), nullable=True))
    op.add_column('risks', sa.Column('vulnerability', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'risks', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.drop_column('risks', 'vulnerability')
    op.drop_column('risks', 'threat')
    op.drop_column('risks', 'asset_id')
    op.drop_constraint(None, 'risk_control_mappings', type_='foreignkey')
    op.alter_column('risk_control_mappings', 'control_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('risk_control_mappings', 'framework_control_id')
    op.drop_column('assets', 'availability')
    op.drop_column('assets', 'integrity')
    op.drop_column('assets', 'confidentiality')
    # ### end Alembic commands ###
