"""add_framework_control_id_to_ticket

Revision ID: 446d7a089740
Revises: a10ff2dfb3c0
Create Date: 2026-03-13 04:31:52.757849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446d7a089740'
down_revision: Union[str, Sequence[str], None] = 'a10ff2dfb3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('framework_control_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'framework_controls', ['framework_control_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'framework_control_id')
    # ### end Alembic commands ###
