"""make_risk_category_id_nullable

Revision ID: 9a4338637084
Revises: bbc7f6f3b0ae
Create Date: 2026-03-15 05:56:42.399655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4338637084'
down_revision: Union[str, Sequence[str], None] = 'bbc7f6f3b0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risks', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risks', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
