"""add_framework_id_to_control_applicability

Revision ID: a10ff2dfb3c0
Revises: 43d8a6d5e7fe
Create Date: 2026-03-13 04:23:27.254872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10ff2dfb3c0'
down_revision: Union[str, Sequence[str], None] = '43d8a6d5e7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_applicability', sa.Column('framework_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'control_applicability', 'frameworks', ['framework_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'control_applicability', type_='foreignkey')
    op.drop_column('control_applicability', 'framework_id')
    # ### end Alembic commands ###
