"""add_invitation_system_columns_v2

Revision ID: bbc7f6f3b0ae
Revises: f6067e98e5c7
Create Date: 2026-03-13 20:23:23.453810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc7f6f3b0ae'
down_revision: Union[str, Sequence[str], None] = 'f6067e98e5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('infrastructure', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('data_types', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('created_by', sa.UUID(), nullable=True))
    op.alter_column('organizations', 'employee_count',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'organizations', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('invitation_status', sa.String(), server_default='pending', nullable=False))
    op.add_column('users', sa.Column('invited_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('invited_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('organization_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_name')
    op.drop_column('users', 'invited_at')
    op.drop_column('users', 'invited_by')
    op.drop_column('users', 'invitation_status')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.alter_column('organizations', 'employee_count',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('organizations', 'created_by')
    op.drop_column('organizations', 'onboarding_completed')
    op.drop_column('organizations', 'data_types')
    op.drop_column('organizations', 'infrastructure')
    # ### end Alembic commands ###
