"""Phase 2 standardized Asset and Risk models

Revision ID: f6067e98e5c7
Revises: 7eb8e89c4861
Create Date: 2026-03-13 05:24:34.101491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6067e98e5c7'
down_revision: Union[str, Sequence[str], None] = '7eb8e89c4861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'asset_type', new_column_name='type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_type', postgresql.ENUM('data', 'software', 'hardware', 'service', 'personnel', 'physical', 'server', 'db', 'app', name='assettype'), autoincrement=False, nullable=False))
    op.drop_column('assets', 'type')
    # ### end Alembic commands ###
