"""add_notification_fields

Revision ID: f77beaea7328
Revises: 07390fbae0fd
Create Date: 2026-03-17 19:13:51.331659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77beaea7328'
down_revision: Union[str, Sequence[str], None] = '07390fbae0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns WHERE table_name='notifications'"
    ))
    existing_columns = {row[0] for row in result}

    if 'title' not in existing_columns:
        op.add_column('notifications', sa.Column('title', sa.String(), nullable=True))
    if 'link_url' not in existing_columns:
        op.add_column('notifications', sa.Column('link_url', sa.String(), nullable=True))
    if 'entity_type' not in existing_columns:
        op.add_column('notifications', sa.Column('entity_type', sa.String(), nullable=True))
    if 'entity_id' not in existing_columns:
        op.add_column('notifications', sa.Column('entity_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'entity_type')
    op.drop_column('notifications', 'link_url')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
