"""fix linked_risk_id column final

Revision ID: f995e18518e8
Revises: 07390fbae0fd
Create Date: 2026-03-17 21:24:23.702006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f995e18518e8'
down_revision: Union[str, Sequence[str], None] = '07390fbae0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    controls_result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns WHERE table_name='controls'"
    ))
    controls_existing_columns = {row[0] for row in controls_result}

    if 'linked_risk_id' not in controls_existing_columns:
        op.add_column('controls', sa.Column('linked_risk_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'controls', 'risks', ['linked_risk_id'], ['id'])
    op.alter_column('document_analyses', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)

    document_analyses_result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns WHERE table_name='document_analyses'"
    ))
    document_analyses_existing_columns = {row[0] for row in document_analyses_result}

    if 'summary' in document_analyses_existing_columns:
        op.drop_column('document_analyses', 'summary')

    notifications_result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns WHERE table_name='notifications'"
    ))
    notifications_existing_columns = {row[0] for row in notifications_result}

    if 'link_url' in notifications_existing_columns:
        op.drop_column('notifications', 'link_url')
    if 'entity_id' in notifications_existing_columns:
        op.drop_column('notifications', 'entity_id')
    if 'title' in notifications_existing_columns:
        op.drop_column('notifications', 'title')
    if 'entity_type' in notifications_existing_columns:
        op.drop_column('notifications', 'entity_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('link_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document_analyses', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('document_analyses', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'controls', type_='foreignkey')
    op.drop_column('controls', 'linked_risk_id')
    # ### end Alembic commands ###
